<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://localhost/soap/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://localhost/soap/">
<types>
<xsd:schema targetNamespace="http://localhost/soap/">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="comprobarTipoRequest">
<part name="id" type="xsd:int"/>
</message>
<message name="comprobarTipoResponse">
<part name="return" type="xsd:int"/>
</message>
<portType name="PortType">
<operation name="comprobarTipo">
<documentation>Documentacion de comprobarTipo</documentation>
<input message="tns:comprobarTipoRequest"/>
<output message="tns:comprobarTipoResponse"/>
</operation>
</portType>
<binding name="Binding" type="tns:PortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="comprobarTipo">
<soap:operation soapAction="http://localhost/PabloDeSchouwer/servicios/servicio.php/comprobarTipo" style="rpc"/>
<input>
<soap:body use="literal" namespace=""/>
</input>
<output>
<soap:body use="literal" namespace=""/>
</output>
</operation>
</binding>
<service name="">
<port name="Port" binding="tns:Binding">
<soap:address location="http://localhost/PabloDeSchouwer/servicios/servicio.php"/>
</port>
</service>
</definitions>